### ISSUE TITLE
Unify the "Groups audience" and "Other groups" fields for group admins

### ISSUE THREAD

**Issue by pfrenssen** [amitaibu/og#148]
Currently when managing group content there are two fields shown to group admins:
- "Groups audience" which can be used to select groups the admin is a member of.
- "Other groups" which can be used to select groups the admin is not a member of.

This seems like a UX problem to me. Why don't we simply show one field, that shows all the groups for admins, and only the groups the user is a member of for everyone else?

Are there any particular reasons for this that I might be overlooking?

**Comment by amitaibu** [comment]
Yes, there's a good reason :) 

As a site admin, I may still have "My groups" - and that a limited list, a required one that expects only a single group via a select widget. But since I'm a privileged user I should be able to select also "Other groups" from a much bigger list via an auto-complete widget.

Each widget will get a different validation.
