### ISSUE TITLE
Remove the OG membership reference field

### ISSUE THREAD

**Issue by pfrenssen** [amitaibu/og#195]
We now have the `OgMembership` entity to keep track of the groups a user is subscribed to. We no longer need a field to store this data in. Having this data duplicated in two locations makes everything much more complicated and confusing.

**Comment by pfrenssen** [comment]
We still need this field so users can edit their memberships in their user account form. We are not using the field for storage.

**Comment by damiankloip** [comment]
> Having this data duplicated in two locations makes everything much more complicated and confusing.

Ha, so that is the path that was chosen when the decision was made to use regular field storage for groups. We went from one storage table for everything to now og_memberships for users and a field for each group content field...

I think maybe you mis-understand the purpose of it a little. We are totally using the field for storage, display, and forms I think. It is just that we store memberships in our own table, with OgMemership entities instead of regular entity references.

**Comment by pfrenssen** [comment]
I'm going to have to take a deeper look at it, I was making the wrong assumption that the field was "the old way" and the OgMembership entity was "the new way".

In our project we don't have the field added to the user entity, and joining and leaving groups works perfectly fine, this was giving me the impression that the field had become completely redundant.

So if the actual memberships are stored in the OgMembership entity, what is stored on the field then?

**Comment by damiankloip** [comment]
The reference field deals with OgMembership entities, no? Unless lots of
other stuff changed since I last looked of course :)

**Comment by amitaibu** [comment]
> So if the actual memberships are stored in the OgMembership entity, what is stored on the field then?

Everything :) The field's storage _is_ the OgMembership entity when it's attached to a user entity.

If it's a attached to a non-user entity, then the field storage is the default one.

**Comment by pfrenssen** [comment]
Oh I get it now! Wow this stuff is really great, Drupal 8 is amazing :smile:

**Comment by amitaibu** [comment]
🏆
