### ISSUE TITLE
Outline what repo collaborators are allowed to do

### ISSUE THREAD

**Issue by pfrenssen** [amitaibu/og#91]
I have recently been given push access to the repo for which I am very grateful. Can we discuss what would be acceptable for collaborators to push without the supervision of @amitaibu?

Some things which would be nice, and are usually not worth it to open separate PR's for:
- Fixing typos.
- Adding documentation.
- Obvious small fixes?

Is it acceptable for us to do this? Shall we open a separate branch for these small fixes so it can be reviewed before merging back to master?

**Comment by amitaibu** [comment]
I'd still want to be the one that does the merges - mainly because it will make sure that I can have a final look, and see that things are aligned with OG's concepts.

I've also added a `Ready for review` label, you can add to a PR, or you can assign to me when ready.

With that said, if you see some really stupid typo/ trivial mistakes then I guess a PR that you merge yourself is fine.

**Comment by amitaibu** [comment]
btw, the reason for adding collaborators, is so that you could create the branches under `amitaibu/og` - thus allow others to easily collaborate on the PRs.

I hope it answers the question :)

**Comment by pfrenssen** [comment]
That clears it up perfectly, thanks!

**Comment by amitaibu** [comment]
> Outline what repo collaborators are allowed to do

Meet each other and have a beer together :wink: 

![20151216_192524](https://cloud.githubusercontent.com/assets/125707/11851322/71233582-a432-11e5-83aa-bc4682f64572.jpg)

**Comment by dawehner** [comment]
The beard comes back!

**Comment by amitaibu** [comment]
@damiankloip @chx - tl;dr - collaborators get a free beer (or tea) when I meet them :wink:
